apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: consumer-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: consumer-consumer
  duration: 30s